name: load_testing_project
description: A project for load testing
dependencies:
  http: any
  json_serializable: any
  ninja_prime: ^2.0.0
  otp: ^3.2.0
  path_provider: ^2.1.5
dev_dependencies:
  build_runner: any
  test: ^1.26.3

environment:
  sdk: ^3.9.2
